import { readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { assertOgCoverage } from "./lib/og-coverage.js";

const ROOT = resolve(process.cwd(), "../greyradius-website");

type PageDef = {
  file: string;
  ogImage: string;
};

const pages: PageDef[] = [
  { file: "index.html",                                      ogImage: "/assets/images/og-homepage.png" },
  { file: "careers.html",                                    ogImage: "https://greyradius.com/assets/images/og-careers.png" },
  { file: "og-preview.html",                                 ogImage: "/assets/images/og-generic.png" },
  { file: "legal/privacy.html",                              ogImage: "https://greyradius.com/assets/images/og-privacy.png" },
  { file: "legal/terms.html",                                ogImage: "https://greyradius.com/assets/images/og-terms.png" },

  { file: "services/index.html",                             ogImage: "/assets/images/og-services.png" },
  { file: "services/opportunity-assessment.html",            ogImage: "/assets/images/og-svc-opportunity.png" },
  { file: "services/feasibility-and-tev.html",              ogImage: "/assets/images/og-svc-feasibility.png" },
  { file: "services/market-entry-execution.html",           ogImage: "/assets/images/og-svc-market-entry.png" },
  { file: "services/gtm-execution-as-a-service.html",       ogImage: "/assets/images/og-svc-gtm.png" },
  { file: "services/pitchbook-and-fundraising.html",        ogImage: "/assets/images/og-svc-pitchbook.png" },
  { file: "services/ai-consulting-and-transformation.html", ogImage: "/assets/images/og-svc-ai.png" },

  { file: "industries/index.html",                          ogImage: "/assets/images/og-industries.png" },
  { file: "industries/bfsi.html",                           ogImage: "/assets/images/og-ind-bfsi.png" },
  { file: "industries/cpg-fmcg-retail.html",                ogImage: "/assets/images/og-ind-cpg.png" },
  { file: "industries/energy-and-chemicals.html",           ogImage: "/assets/images/og-ind-energy.png" },
  { file: "industries/healthcare-and-life-sciences.html",   ogImage: "/assets/images/og-ind-healthcare.png" },
  { file: "industries/investment-banks-and-pe.html",        ogImage: "/assets/images/og-ind-investment.png" },
  { file: "industries/technology.html",                     ogImage: "/assets/images/og-ind-technology.png" },

  { file: "about/index.html",                               ogImage: "/assets/images/og-about.png" },
  { file: "about/team.html",                                ogImage: "/assets/images/og-about.png" },
  { file: "about/method.html",                              ogImage: "/assets/images/og-about.png" },
  { file: "about/why-greyradius.html",                      ogImage: "/assets/images/og-about.png" },

  { file: "contact.html",                                   ogImage: "/assets/images/og-contact.png" },

  { file: "case-studies/index.html",                        ogImage: "/assets/images/og-case-studies.png" },
  { file: "case-studies/agri-chemical-gtm.html",            ogImage: "/assets/images/og-cs-agri-chemical.png" },
  { file: "case-studies/alloy-metals-sea-expansion.html",   ogImage: "/assets/images/og-cs-alloy-metals.png" },
  { file: "case-studies/coal-mining-enclosed-transport.html", ogImage: "/assets/images/og-cs-coal-mining.png" },
  { file: "case-studies/drone-startup-gtm.html",            ogImage: "/assets/images/og-cs-drone-startup.png" },
  { file: "case-studies/elearning-gcc-expansion.html",      ogImage: "/assets/images/og-cs-elearning.png" },
  { file: "case-studies/eye-care-pharma-market-entry.html", ogImage: "/assets/images/og-cs-eye-care.png" },
  { file: "case-studies/hospital-chain-canada.html",        ogImage: "/assets/images/og-cs-hospital-canada.png" },
  { file: "case-studies/nativfresh-cpg-gtm.html",           ogImage: "/assets/images/og-cs-nativfresh.png" },
  { file: "case-studies/oncology-abstracts.html",           ogImage: "/assets/images/og-cs-oncology.png" },
  { file: "case-studies/retail-market-entry.html",          ogImage: "/assets/images/og-cs-retail-market.png" },
  { file: "case-studies/saas-product-market-fit.html",      ogImage: "/assets/images/og-cs-saas-pmf.png" },
  { file: "case-studies/trinetra-gtm.html",                 ogImage: "/assets/images/og-cs-trinetra.png" },

  { file: "insights/index.html",                                         ogImage: "/assets/images/og-insights.png" },
  { file: "insights/winning-in-saturated-markets.html",                  ogImage: "/assets/images/og-ins-saturated-markets.png" },
  { file: "insights/ai-hype-to-business-results.html",                   ogImage: "/assets/images/og-ins-ai-hype.png" },
  { file: "insights/consultants-vs-inhouse-strategy-team.html",          ogImage: "/assets/images/og-ins-consultants-vs.png" },
  { file: "insights/cost-transformation-not-cost-cutting.html",          ogImage: "/assets/images/og-ins-cost-transform.png" },
  { file: "insights/elearning-retention-gtm-strategy.html",              ogImage: "/assets/images/og-ins-elearning-retention.png" },
  { file: "insights/gcc-renewable-energy-market-entry.html",             ogImage: "/assets/images/og-ins-gcc-renewable.png" },
  { file: "insights/healthcare-ai-operational-readiness.html",           ogImage: "/assets/images/og-ins-healthcare-ai.png" },
  { file: "insights/india-drone-sector-market-entry.html",               ogImage: "/assets/images/og-ins-india-drone.png" },
  { file: "insights/market-expansion-strategy-failures.html",            ogImage: "/assets/images/og-ins-market-expansion-failures.png" },
  { file: "insights/msme-execution-systems-productivity.html",           ogImage: "/assets/images/og-ins-msme-execution.png" },
  { file: "insights/pharma-clinical-trial-decision-intelligence.html",   ogImage: "/assets/images/og-ins-pharma-clinical.png" },
  { file: "insights/plg-vs-slg-which-gtm-model-fits.html",              ogImage: "/assets/images/og-ins-plg-vs-slg.png" },
  { file: "insights/retail-expansion-market-understanding.html",         ogImage: "/assets/images/og-ins-retail-expansion.png" },
  { file: "insights/saas-growth-customer-intelligence.html",             ogImage: "/assets/images/og-ins-saas-growth.png" },
  { file: "insights/saas-international-expansion-model.html",            ogImage: "/assets/images/og-ins-saas-international.png" },
  { file: "insights/standard-of-care-benchmarking-healthcare.html",      ogImage: "/assets/images/og-ins-standard-of-care.png" },
  { file: "insights/supply-chain-resilience-board-strategy.html",        ogImage: "/assets/images/og-ins-supply-chain-resilience.png" },
  { file: "insights/uae-consumer-goods-market-entry.html",               ogImage: "/assets/images/og-ins-uae-consumer.png" },
  // ─── Auto-generated coverage entries (fix-og-coverage.ts) ─────────────────────
  { file: "business-setup-consultants-uae.html",                          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/africa-agritech-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/agritech-southeast-asia.html",             ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/ethiopia-market-entry.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/gulf-agritech-entry.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/gulf-food-security.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/india-agritech-deep-dive.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/india-agritech-entry.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/rwanda-market-entry.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/tanzania-market-entry.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/agritech/vertical-farming.html",                    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ai-ml-platforms/ai-agents-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ai-ml-platforms/digital-twin.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ai-ml-platforms/generative-ai-market-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ai-ml-platforms/gulf-ai-platform-enterprise.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ai-ml-platforms/india-ai-platform-enterprise.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ai-ml-platforms/quantum-computing-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/beauty-personal-care/africa-beauty-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/beauty-personal-care/beauty-personal-care-gcc.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/beauty-personal-care/beauty-personal-care-india.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/beauty-personal-care/beauty-personal-care-southeast-asia.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/beauty-personal-care/halal-cosmetics.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/bfsi/capital-markets.html",                         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/bfsi/embedded-finance.html",                        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/bfsi/fintech-payments.html",                        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/bfsi/india-bfsi-digital-transformation.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/bfsi/india-gulf-financial-services.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/bfsi/insurtech.html",                               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/bfsi/wealthtech.html",                              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/africa-carbon-markets-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/africa-climate-tech.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/carbon-capture.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/carbon-credits-market-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/circular-economy.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/climate-fintech.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/esg-reporting.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/gulf-carbon-markets-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/gulf-sustainability-financing.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/india-carbon-markets-deep-dive.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/india-carbon-markets-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/india-climate-tech.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/southeast-asia-carbon-markets-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/carbon-markets/southeast-asia-climate-tech.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/corporate-learning/africa-corporate-learning.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/corporate-learning/edtech-upskilling.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/corporate-learning/gulf-corporate-learning.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/corporate-learning/india-corporate-learning.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/corporate-learning/southeast-asia-corporate-learning.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/africa-fmcg-distribution.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/africa-fmcg-market-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/beauty-personal-care.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/cambodia-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/colombia-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/direct-to-consumer.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/egypt-market-entry.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/food-beverage.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/franchise-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/gulf-fmcg-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/gulf-retail-market-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/halal-food.html",                   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/health-supplements.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/india-d2c-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/india-fmcg-distribution.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/india-gulf-fmcg-combined.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/india-gulf-india-combined.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/indonesia-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/luxury-goods.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/malaysia-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/modest-fashion.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/morocco-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/myanmar-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/nigeria-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/pakistan-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/pet-economy.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/philippines-market-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/south-africa-market-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/southeast-asia-fmcg-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/southeast-asia-retail-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cpg-fmcg-retail/uzbekistan-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cybersecurity/africa-cybersecurity-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cybersecurity/cybersecurity-gcc.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cybersecurity/cybersecurity-services-india.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/cybersecurity/cybersecurity-southeast-asia.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/data-centers/africa-data-centre.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/data-centers/data-centers-gcc.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/data-centers/data-centers-india.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/data-centers/data-centers-southeast-asia.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/data-centers/hyperscale-data-center.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/defence-aerospace/defence-aerospace-gcc.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/defence-aerospace/defence-manufacturing-india.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/defence-aerospace/mro-aerospace-southeast-asia.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/diagnostics/africa-diagnostics-pathology-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/diagnostics/digital-diagnostics.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/diagnostics/gulf-diagnostics-pathology-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/diagnostics/india-diagnostics-pathology-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/diagnostics/medtech-diagnostics-ai.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/diagnostics/southeast-asia-diagnostics-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/drones/africa-drones-technology-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/drones/agricultural-drones.html",                   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/drones/commercial-drone-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/drones/gulf-drones-technology-entry.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/drones/india-drones-technology-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/drones/southeast-asia-drones-technology-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/b2b-marketplace.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/cross-border-ecommerce.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/gulf-ecommerce-tech-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/india-b2b-marketplace.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/india-ecommerce-market-entry.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/india-ecommerce-tech-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/social-commerce.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/ecommerce-tech/southeast-asia-ecommerce-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-and-edtech.html",                         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/africa-edtech-market-entry.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/africa-edtech-platform-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/corporate-learning.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/gulf-edtech-platform-entry.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/gulf-education-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/higher-education.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/india-edtech-market-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/india-edtech-platform-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/india-gulf-education-combined.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/k12-edtech.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/education-edtech/southeast-asia-edtech-platform-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/africa-electric-vehicle-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/autonomous-vehicles.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/ev-battery-market-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/ev-two-three-wheeler.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/evtol-urban-air-mobility.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/gulf-smart-mobility.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/india-electric-vehicle-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/india-electric-vehicle-market.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/india-mobility-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/electric-vehicles/telematics-fleet-tech.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/embedded-finance/bnpl-embedded-finance.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/embedded-finance/gulf-embedded-finance.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/embedded-finance/india-embedded-finance.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/biofuels-saf.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/cleantech.html",                   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/energy-storage.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/iran-market-entry-assessment.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/nuclear-smr.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/oil-gas.html",                     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/oman-market-entry.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/qatar-market-entry.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/renewable-energy.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/smart-grids.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-chemicals/water-technology.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-storage/africa-energy-storage-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-storage/battery-as-a-service.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-storage/battery-recycling.html",             ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-storage/gulf-energy-storage-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-storage/india-energy-storage-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-storage/india-renewable-energy-storage.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/energy-storage/southeast-asia-energy-storage-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/africa-b2b-saas-enterprise-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/b2b-saas-emerging-markets.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/govtech.html",                      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/gulf-b2b-saas-enterprise-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/gulf-b2b-services.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/india-b2b-saas-enterprise-gtm.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/india-b2b-saas-pricing.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/india-b2b-saas-vertical.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/india-saas-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/legaltech.html",                    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/southeast-asia-b2b-saas-enterprise.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/enterprise-saas/southeast-asia-enterprise-saas.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/africa-agrifintech-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/africa-digital-payments.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/africa-fintech-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/africa-fintech-mobile-money.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/africa-payment-infrastructure.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/agrifintech.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/digital-payments-infrastructure.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/ed-fintech.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/ghana-market-entry.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/gulf-fintech-market-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/gulf-open-banking-fintech.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/india-fintech-b2b.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/india-fintech-infrastructure.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/india-fintech-lending.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/india-fintech-market-entry.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/india-upi-fintech-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/india-wealth-management.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/kenya-market-entry.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/neobank-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/open-banking.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/regtech.html",                     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/remittance-cross-border.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/senegal-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/southeast-asia-fintech-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/fintech-payments/southeast-asia-fintech-payments.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/food-beverage/africa-food-beverage.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/food-beverage/gulf-food-beverage-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/food-beverage/india-food-beverage-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/food-beverage/india-food-tech.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/food-beverage/plant-based-food.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/food-beverage/precision-fermentation.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/food-beverage/southeast-asia-food-beverage.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/foodtech/alternative-protein-southeast-asia.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/foodtech/foodtech-cloud-kitchens-india.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/foodtech/foodtech-gcc.html",                        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/freight-cargo/gulf-freight-cargo.html",             ogImage: "/assets/images/og-generic.png" },
  { file: "industries/freight-cargo/india-freight-cargo.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/freight-cargo/port-logistics-parks.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/freight-cargo/port-maritime.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/gaming-esports/gaming-esports-gcc.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/gaming-esports/gaming-esports-india.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/gaming-esports/gaming-southeast-asia.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/gaming/africa-gaming.html",                         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/gaming/online-gaming-igaming.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/africa-consumer-research.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/africa-market-entry.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/gulf-africa-market-gateway.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/gulf-enterprise-buyer-guide.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/gulf-localisation-strategy.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/gulf-market-entry.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/gulf-vision-2030-opportunities.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/india-africa-market-gateway.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/india-enterprise-buyer-guide.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/india-market-entry.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/india-regulatory-guide.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/southeast-asia-enterprise-buyer-guide.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/geographies/southeast-asia-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/global-capability-centers/gcc-scaling-transformation-india.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/global-capability-centers/gcc-setup-india.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/green-hydrogen/africa-green-hydrogen-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/green-hydrogen/green-hydrogen-market-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/green-hydrogen/gulf-green-hydrogen-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/green-hydrogen/hydrogen-fuel-cell.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/green-hydrogen/hydrogen-infrastructure.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/green-hydrogen/india-green-hydrogen-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/green-hydrogen/southeast-asia-green-hydrogen-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/health-supplements/africa-health-supplements-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/health-supplements/functional-food.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/health-supplements/gulf-health-supplements-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/health-supplements/india-consumer-health.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/health-supplements/india-health-supplements-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/health-supplements/personalised-nutrition.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/health-supplements/southeast-asia-health-supplements-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/africa-healthcare-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/diagnostics.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/genomics-precision-medicine.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/gulf-healthcare-investment.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/gulf-healthcare-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/gulf-silver-economy.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/healthtech.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/india-genomics-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/india-healthcare-infrastructure.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/longevity-biotech.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/medical-devices.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/neurotechnology.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/pharma.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthcare-life-sciences/silver-economy.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/africa-healthtech-market-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/femtech-market-entry.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/gulf-healthcare-data.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/gulf-healthcare-technology.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/gulf-healthtech-enterprise-gtm.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/gulf-medtech-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/healthcare-ai-platforms.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/india-digital-health-platform.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/india-healthtech-market-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/longevity-health.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/southeast-asia-healthcare-technology.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/southeast-asia-healthtech-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/healthtech/southeast-asia-healthtech-scale.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/higher-education/africa-higher-education.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/higher-education/gulf-higher-education.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/higher-education/india-higher-education.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/higher-education/islamic-education.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/higher-education/southeast-asia-higher-education.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/gulf-hospitality-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/gulf-hospitality-tech-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/gulf-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/gulf-tourism-technology.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/halal-tourism.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/hotels-resorts.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/india-hospitality-tech-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/medical-tourism.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/saudi-arabia-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/sports-wellness.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/thailand-market-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hospitality-tourism/uae-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hrtech/africa-hrtech.html",                         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hrtech/gig-economy-platforms.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hrtech/gulf-hrtech-market-entry.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hrtech/india-hrtech-market-entry.html",             ogImage: "/assets/images/og-generic.png" },
  { file: "industries/hrtech/southeast-asia-hrtech.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/industrials-manufacturing-and-infrastructure.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/africa-insurance-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/digital-health-insurance.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/gulf-health-insurance-market.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/gulf-insurtech-entry.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/india-insurance-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/india-insurtech-digital-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/india-insurtech-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/insurtech-agriculture.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/insurtech-embedded.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/insurtech/southeast-asia-insurance-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/islamic-finance/gulf-islamic-banking.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/islamic-finance/gulf-islamic-finance-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/islamic-finance/india-islamic-finance-entry.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/islamic-finance/india-islamic-finance.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/islamic-finance/islamic-economy-platforms.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/islamic-finance/islamic-fintech-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/islamic-finance/southeast-asia-islamic-finance-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/last-mile-delivery/africa-last-mile.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/last-mile-delivery/food-delivery-platform.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/last-mile-delivery/gulf-last-mile.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/last-mile-delivery/india-last-mile.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/last-mile-delivery/reverse-logistics.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/africa-logistics-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/africa-logistics-supply-chain-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/africa-market-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/cold-chain.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/freight-cargo.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/gulf-logistics-automation.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/gulf-logistics-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/gulf-logistics-supply-chain.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/india-logistics-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/india-logistics-supply-chain-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/india-supply-chain-resilience.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/last-mile-delivery.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/southeast-asia-logistics-supply-chain.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/southeast-asia-logistics-technology.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/southeast-asia-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/logistics-supply-chain/supply-chain-tech.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/3d-printing-manufacturing.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/advanced-materials.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/aerospace-defense.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/africa-manufacturing-industrial-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/africa-manufacturing-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/agritech.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/bangladesh-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/electric-vehicles.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/gulf-advanced-manufacturing-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/india-advanced-manufacturing-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/india-coastal-infrastructure.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/india-manufacturing-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/india-manufacturing-technology.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/india-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/robotics-automation.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/satellite-connectivity.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/smart-manufacturing.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/southeast-asia-manufacturing-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/southeast-asia-manufacturing-technology.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/space-tech-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/sri-lanka-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/sustainable-packaging.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/synthetic-biology.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/manufacturing-industrials/vietnam-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/creator-economy.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/gaming.html",                   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/gulf-media-entertainment-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/india-creator-economy.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/india-media-entertainment-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/india-media-entertainment.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/sports-tech.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/media-entertainment/streaming-ott.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/medical-devices/africa-medical-devices-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/medical-devices/gulf-medical-devices.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/medical-devices/hospital-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/medical-devices/india-medical-devices-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/medical-devices/medtech-wearables.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/medical-devices/southeast-asia-medical-devices.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/mental-health-tech/gulf-mental-health.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/mental-health-tech/india-mental-health.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/mental-health-tech/mental-health-corporate.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/mental-health-tech/mental-health-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/mining-metals/critical-minerals-india.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/mining-metals/metals-diversification-gcc.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/mining-metals/mining-metals-africa.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/pharma/africa-pharma-market-entry.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/pharma/gulf-pharma-market-entry.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/pharma/halal-pharma.html",                          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/pharma/india-pharma-market-entry.html",             ogImage: "/assets/images/og-generic.png" },
  { file: "industries/pharma/pharma-distribution.html",                   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/pharma/southeast-asia-pharma.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/africa-proptech-entry.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/africa-real-estate-market-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/gulf-construction-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/gulf-proptech-real-estate.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/gulf-real-estate-market-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/india-proptech-entry.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/india-proptech-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/india-real-estate-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/proptech-construction.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/proptech/southeast-asia-proptech-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/quick-commerce/quick-commerce-gcc.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/quick-commerce/quick-commerce-india.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/rare-earth-metals/africa-rare-earth.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/rare-earth-metals/gulf-rare-earth.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/rare-earth-metals/india-rare-earth.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/rare-earth-metals/rare-earth-supply-chain.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/rare-earth-metals/southeast-asia-rare-earth.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/real-estate-and-infrastructure.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/real-estate-infrastructure/data-centers.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/real-estate-infrastructure/proptech.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/real-estate-infrastructure/reit-consulting.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/real-estate-infrastructure/smart-city-consulting.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/reit-consulting/digital-infrastructure-reit.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/reit-consulting/gulf-reit-real-estate-funds.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/reit-consulting/india-reit-real-estate-funds.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/reit-consulting/real-estate-tokenisation.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/africa-energy-market-entry.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/africa-renewable-energy-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/africa-solar-energy-scale.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/community-solar.html",             ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/gulf-energy-transition.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/gulf-renewable-energy-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/india-energy-market-entry.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/india-gulf-energy-combined.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/india-renewable-energy-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/india-renewable-hydrogen.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/offshore-wind-market-entry.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/renewable-energy/southeast-asia-renewable-energy-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/residential-development/affordable-housing.html",   ogImage: "/assets/images/og-generic.png" },
  { file: "industries/residential-development/africa-residential-development.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/residential-development/gulf-residential-development.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/residential-development/india-residential-development.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/robotics-automation/industrial-robotics-india.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/robotics-automation/robotics-automation-gcc.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/robotics-automation/warehouse-automation-southeast-asia.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/satellite-connectivity/africa-satellite-connectivity-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/satellite-connectivity/gulf-satellite-connectivity-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/satellite-connectivity/india-satellite-connectivity-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/satellite-connectivity/india-space-tech.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/satellite-connectivity/nano-satellite.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/satellite-connectivity/southeast-asia-satellite-connectivity-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/semiconductors/gulf-semiconductor-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/semiconductors/india-semiconductor-market-entry.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/semiconductors/osat-atmp-southeast-asia.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/semiconductors/semiconductor-fab-consulting.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/semiconductors/semiconductor-fab-ecosystem-india.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/semiconductors/semiconductor-supply-chain-gcc.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/semiconductors/southeast-asia-semiconductor.html",  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/africa-mobile-internet.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/africa-technology-market-entry.html",    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/cloud-infrastructure.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/cybersecurity.html",                     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/data-analytics.html",                    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/gulf-ai-market-entry.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/gulf-ai-national-strategy.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/gulf-data-centres.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/gulf-enterprise-ai-deployment.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/gulf-smart-infrastructure.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/gulf-technology-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/gulf-water-technology.html",             ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/hrtech.html",                            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/india-deep-tech-market-entry.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/india-defence-technology.html",          ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/india-gulf-technology-entry.html",       ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/india-iot-smart-city.html",              ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/india-semiconductor-design.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/india-telecom-market-entry.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/india-urban-infrastructure.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/singapore-market-entry.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/smart-home.html",                        ogImage: "/assets/images/og-generic.png" },
  { file: "industries/technology/southeast-asia-govtech.html",            ogImage: "/assets/images/og-generic.png" },
  { file: "industries/telecom-5g/5g-enterprise-india.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "industries/telecom-5g/5g-private-networks-southeast-asia.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/telecom-5g/telecom-infrastructure-africa.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "industries/water-wastewater/desalination-water-gcc.html",      ogImage: "/assets/images/og-generic.png" },
  { file: "industries/water-wastewater/water-infrastructure-africa.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/water-wastewater/water-wastewater-treatment-india.html", ogImage: "/assets/images/og-generic.png" },
  { file: "industries/wealthtech/africa-wealthtech.html",                 ogImage: "/assets/images/og-generic.png" },
  { file: "industries/wealthtech/wealthtech-gcc.html",                    ogImage: "/assets/images/og-generic.png" },
  { file: "industries/wealthtech/wealthtech-india.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "industries/wealthtech/wealthtech-robo-advisor.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "industries/wealthtech/wealthtech-southeast-asia.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "insights/b2b-saas-pricing-india.html",                         ogImage: "/assets/images/og-generic.png" },
  { file: "insights/gtm-strategy-emerging-markets.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "insights/gulf-market-entry-mistakes.html",                     ogImage: "/assets/images/og-generic.png" },
  { file: "insights/how-to-enter-india-market.html",                      ogImage: "/assets/images/og-generic.png" },
  { file: "insights/india-distributor-evaluation-framework.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/abb-gridserve-ev-india-pli-july13-19-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/afdb-gotion-catl-spain-ev-july20-26-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/commercial-ev-electrification-battery-trends-june-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/commercial-ev-electrification-july6-12-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/gm-saic-evgo-byd-brazil-ev-aug3-9-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/index.html",                      ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/nio-xpeng-rivian-renault-byd-ev-jul27-aug2-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/sodium-ion-batteries-v2g-charging-june-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/charged/tesla-byd-q2-ev-deliveries-storage-july-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/index.html",                              ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/anthropic-eu-gigafactory-scale-ai-meta-blackrock-jul27-aug2-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/enterprise-ai-agentic-chips-july13-19-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/enterprise-ai-deployment-compute-financing-july-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/enterprise-ai-gpt56-july6-12-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/enterprise-ai-infrastructure-cyber-defense-june-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/index.html",                   ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/india-ai-investment-sovereign-infrastructure-june-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/nvidia-sk-amd-helios-intel-ai-july20-26-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-signal/openai-astra-amd-microsoft-india-aug3-9-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/ai-data-centre-meta-alberta-july6-12-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/ai-data-centre-power-investment-consolidation-july-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/ai-power-infrastructure-hyperscale-investment-june-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/amazon-schneider-meta-israel-orange-google-jul27-aug2-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/aws-india-hcltech-data-centre-july13-19-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/hcltech-odisha-digital-realty-google-georgia-july20-26-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/index.html",                    ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-stack/indosat-zankore-microsoft-india-coreweve-indonesia-aug3-9-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/global-fabs-osat-ai-memory-investment-june-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/index.html",                    ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/india-osat-europe-fabs-ai-memory-korea-july-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/ionq-samsung-sk-hynix-lam-research-jul27-aug2-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/samsung-broadcom-amkor-nvidia-intel-packaging-july20-26-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/sk-hynix-micron-july6-12-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/skhynix-terafab-samsung-nand-aug3-9-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/newsletters/the-wafer/tsmc-micron-intel-ireland-july13-19-2026/index.html", ogImage: "/assets/images/og-generic.png" },
  { file: "insights/vision-2030-foreign-companies-market-entry.html",     ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/distributor-search-channel-partners.html",        ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/government-b2g-market-entry.html",                ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/index.html",                                      ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/india-consumer-fmcg-market-entry.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/india-manufacturing-market-entry.html",           ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/india-technology-saas-market-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/indonesia-market-entry.html",                     ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/market-entry-cost.html",                          ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/market-entry-via-acquisition.html",               ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/north-america-entry-for-india-asia-companies.html", ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/saudi-arabia-market-entry.html",                  ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/southeast-asia-manufacturing-entry.html",         ogImage: "/assets/images/og-generic.png" },
  { file: "market-entry/uae-market-entry.html",                           ogImage: "/assets/images/og-generic.png" },
];

const ogImageTag = (src: string) =>
  `  <meta property="og:image" content="${src}">`;
const twitterImageTag = (src: string) =>
  `  <meta name="twitter:image" content="${src}">`;

assertOgCoverage({ imagePages: new Set(pages.map((p) => p.file)) });

let updated = 0;
let replaced = 0;
let skipped = 0;

for (const { file, ogImage } of pages) {
  const path = resolve(ROOT, file);
  let html = readFileSync(path, "utf-8");
  let changed = false;

  // ── og:image ──────────────────────────────────────────────────────────────
  const ogTag = ogImageTag(ogImage);
  if (html.includes('property="og:image"')) {
    const existing = html.match(/property="og:image" content="([^"]+)"/)?.[1];
    if (existing !== ogImage) {
      html = html.replace(/<meta property="og:image"[^>]*>/, ogTag.trim());
      changed = true;
    }
  } else {
    if (html.includes('property="og:description"')) {
      html = html.replace(/(<meta property="og:description"[^>]*>)/, `$1\n${ogTag}`);
    } else if (html.includes('property="og:title"')) {
      html = html.replace(/(<meta property="og:title"[^>]*>)/, `$1\n${ogTag}`);
    } else {
      html = html.replace("</head>", `${ogTag}\n</head>`);
    }
    changed = true;
  }

  // ── twitter:image ─────────────────────────────────────────────────────────
  const twTag = twitterImageTag(ogImage);
  if (html.includes('name="twitter:image"')) {
    const existingTw = html.match(/name="twitter:image" content="([^"]+)"/)?.[1];
    if (existingTw !== ogImage) {
      html = html.replace(/<meta name="twitter:image"[^>]*>/, twTag.trim());
      changed = true;
    }
  } else {
    // Insert after og:image tag so the two stay adjacent
    if (html.includes('property="og:image"')) {
      html = html.replace(/(<meta property="og:image"[^>]*>)/, `$1\n${twTag}`);
    } else {
      html = html.replace("</head>", `${twTag}\n</head>`);
    }
    changed = true;
  }

  if (!changed) {
    console.log(`  SKIP (already correct): ${file}`);
    skipped++;
    continue;
  }

  writeFileSync(path, html, "utf-8");
  const wasReplace = html.includes('property="og:image"');
  if (wasReplace) {
    console.log(`  ↻ ${file}  →  ${ogImage}`);
    replaced++;
  } else {
    console.log(`  ✓ ${file}`);
    updated++;
  }
}

console.log(`\nDone. Added: ${updated}, Replaced: ${replaced}, Skipped: ${skipped}`);
